# Site settings
title: Maria e Niccolo'

# Contact form:
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2a78df #80B3FF
  primary-rgb: "42,120,223" #"128,179,255"
  secondary: 164C94 #FD6E8A
  secondary-dark: 113760 #A2122F

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

plugins:
    - jekyll-leaflet