# Site settings
title: 20 Maggio 2023
email: your-email@domain.com


# Contact form:
contact: static


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: CAE3FF #80B3FF
  primary-rgb: "202,227,255" #"128,179,255"
  secondary: 164C94 #FD6E8A
  secondary-dark: 113760 #A2122F


# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

plugins:
    - jekyll-leaflet